vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'


    mappings:
        registro_solicitud:
            uri_prefix: /submissions
            upload_destination: '%kernel.project_dir%/public/submissions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        registro_cv:
            uri_prefix: /submissions
            upload_destination: '%kernel.project_dir%/public/submissions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        registro_comprobante:
            uri_prefix: /submissions
            upload_destination: '%kernel.project_dir%/public/submissions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        registro_curso:
            uri_prefix: /submissions
            upload_destination: '%kernel.project_dir%/public/submissions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        registro_ref1recom:
            uri_prefix: /submissions
            upload_destination: '%kernel.project_dir%/public/submissions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        registro_ref2recom:
            uri_prefix: /submissions
            upload_destination: '%kernel.project_dir%/public/submissions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer